In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the data

In [3]:
data= pd.read_csv(r'C:\Users\milan\Downloads\mushrooms.csv')

In [5]:
data

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

# Data Exploration
data.shape

In [6]:
data.shape

(8124, 23)

In [7]:
# check missing values
data.isnull().sum()
# no unfilled value

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [9]:
data.nunique()


class                        2
cap-shape                    6
cap-surface                  4
cap-color                   10
bruises                      2
odor                         9
gill-attachment              2
gill-spacing                 2
gill-size                    2
gill-color                  12
stalk-shape                  2
stalk-root                   5
stalk-surface-above-ring     4
stalk-surface-below-ring     4
stalk-color-above-ring       9
stalk-color-below-ring       9
veil-type                    1
veil-color                   4
ring-number                  3
ring-type                    5
spore-print-color            9
population                   6
habitat                      7
dtype: int64

In [10]:
data.dtypes

class                       object
cap-shape                   object
cap-surface                 object
cap-color                   object
bruises                     object
odor                        object
gill-attachment             object
gill-spacing                object
gill-size                   object
gill-color                  object
stalk-shape                 object
stalk-root                  object
stalk-surface-above-ring    object
stalk-surface-below-ring    object
stalk-color-above-ring      object
stalk-color-below-ring      object
veil-type                   object
veil-color                  object
ring-number                 object
ring-type                   object
spore-print-color           object
population                  object
habitat                     object
dtype: object

# Data Cleaning

In [14]:
# drop "veil-type", 'veil-color','gill-attachment','stalk-root',features were reduced to 19 columns
data = data.drop(['veil-color','gill-attachment','stalk-root'], axis = 1)
data.describe()

class cap-shape cap-surface cap-color bruises  odor gill-spacing  \
count   8124      8124        8124      8124    8124  8124         8124   
unique     2         6           4        10       2     9            2   
top        e         x           y         n       f     n            c   
freq    4208      3656        3244      2284    4748  3528         6812   

       gill-size gill-color stalk-shape stalk-surface-above-ring  \
count       8124       8124        8124                     8124   
unique         2         12           2                        4   
top            b          b           t                        s   
freq        5612       1728        4608                     5176   

       stalk-surface-below-ring stalk-color-above-ring stalk-color-below-ring  \
count                      8124                   8124                   8124   
unique                        4                      9                      9   
top                           s                      w                      w   
freq                       4936                   4464                   4384   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148

In [17]:
X = data.iloc[:,1:]
y = data.iloc[:,0].values
X

cap-shape cap-surface cap-color bruises odor gill-spacing gill-size  \
0            x           s         n       t    p            c         n   
1            x           s         y       t    a            c         b   
2            b           s         w       t    l            c         b   
3            x           y         w       t    p            c         n   
4            x           s         g       f    n            w         b   
...        ...         ...       ...     ...  ...          ...       ...   
8119         k           s         n       f    n            c         b   
8120         x           s         n       f    n            c         b   
8121         f           s         n       f    n            c         b   
8122         k           y         n       f    y            c         n   
8123         x           s         n       f    n            c         b   

     gill-color stalk-shape stalk-surface-above-ring stalk-surface-below-ring  \
0             k           e                        s                        s   
1             k           e                        s                        s   
2             n           e                        s                        s   
3             n           e                        s                        s   
4             k           t                        s                        s   
...         ...         ...                      ...                      ...   
8119          y           e                        s                        s   
8120          y           e                        s                        s   
8121          n           e                        s                        s   
8122          b           t                        s                        k   
8123          y           e                        s                        s   

     stalk-color-above-ring stalk-color-below-ring ring-number ring-type  \
0                         w                      w           o         p   
1                         w                      w           o         p   
2                         w                      w           o         p   
3                         w                      w           o         p   
4                         w                      w           o         e   
...                     ...                    ...         ...       ...   
8119                      o                      o           o         p   
8120                      o                      o           o         p   
8121                      o                      o           o         p   
8122                      w                      w           o         e   
8123                      o                      o           o         p   

     spore-print-color population habitat  
0                    k          s       u  
1                    n          n       g  
2                    n          n       m  
3                    k          s       u  
4                    n          a       g  
...                ...        ...     ...  
8119                 b          c       l  
8120                 b          v       l  
8121                 b          c       l  
8122                 w          v       l  
8123                 o          c       l  

[8124 rows x 18 columns]

In [18]:
y

array(['p', 'e', 'e', ..., 'e', 'p', 'e'], dtype=object)

# Encode categorical data

In [25]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
for col in data.columns:
    data[col] = labelencoder.fit_transform(data[col])
 

In [27]:
data

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-spacing  \
0         1          5            2          4        1     6             0   
1         0          5            2          9        1     0             0   
2         0          0            2          8        1     3             0   
3         1          5            3          8        1     6             0   
4         0          5            2          3        0     5             1   
...     ...        ...          ...        ...      ...   ...           ...   
8119      0          3            2          4        0     5             0   
8120      0          5            2          4        0     5             0   
8121      0          2            2          4        0     5             0   
8122      1          3            3          4        0     8             0   
8123      0          5            2          4        0     5             0   

      gill-size  gill-color  stalk-shape  stalk-surface-above-ring  \
0             1           4            0                         2   
1             0           4            0                         2   
2             0           5            0                         2   
3             1           5            0                         2   
4             0           4            1                         2   
...         ...         ...          ...                       ...   
8119          0          11            0                         2   
8120          0          11            0                         2   
8121          0           5            0                         2   
8122          1           0            1                         2   
8123          0          11            0                         2   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  ring-number  ring-type  spore-print-color  \
0                          7            1          4                  2   
1                          7            1          4                  3   
2                          7            1          4                  3   
3                          7            1          4                  2   
4                          7            1          0                  3   
...                      ...          ...        ...                ...   
8119                       5            1          4                  0   
8120                       5            1          4                  0   
8121                       5            1          4                  0   
8122                       7            1          0                  7   
8123                       5            1          4                  4   

      population  habitat  
0              3        5  
1              2        1  
2              2        3  
3              3        5  
4              0        1  
...          ...      ...  
8119           1        2  
8120           4        2  
8121           1        2  
8122           4        2  
8123           1        2  

[8124 rows x 19 columns]

# Splitting the data into train and test

In [26]:
#splitting training data in test, train, test size is 20% of whole train data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

# Logistic Regression

In [24]:
#importing Logistic Regression 
from sklearn.linear_model import LogisticRegression
#creating our model
model1=LogisticRegression()
#applying Logistic Regression on train data
model1.fit(X_train, y_train)

LogisticRegression()

In [29]:
prediction1= model1.predict(X_test)
prediction1

array([0, 1, 1, ..., 1, 1, 1])

# Accuracy score

In [30]:
from sklearn.metrics import accuracy_score 
accuracy_score(prediction1,y_test)

1.0

# Evaluation using confusion matrix

In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, prediction1 )

array([[843,   0],
       [  0, 782]], dtype=int64)

Note: The confusion matrix here describes how many correct predictions and wrong predictions have been made
for class=0 and class=1. Total wrong predictions=0+0=0

# Gaussian Naive Bayes

In [36]:
from sklearn.naive_bayes import GaussianNB
model_naive = GaussianNB()
model_naive.fit(X_train, y_train)

GaussianNB()

In [38]:
y_predict=model_naive.predict(X_test)
y_predict

array([0, 1, 1, ..., 1, 1, 1])

# Evaluation using confusion matrix and accuracy score

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score 

In [39]:
confusion_matrix(y_test, y_predict )

array([[819,  24],
       [  0, 782]], dtype=int64)

Note: The confusion matrix here describes how many correct predictions and wrong predictions have been made
for class=0 and class=1. Total wrong predictions=0+24=24

In [41]:
accuracy_score(y_test,y_predict)

0.9852307692307692